/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'midnight-base': '#0D0C11',
        'dark-surface': '#16151C',
        'elevated-surface': '#1F1D26',
        'lavender': '#D0BCFF',
        'mint': '#B9F2C8',
        'pink-soft': '#FFD8E4',
        'soft-white': '#ECE9F1',
        'cool-grey': '#A39FB0',
        'dim-grey': '#75717F',
        'on-surface': '#ECE9F1',
        'on-surface-variant': '#A39FB0',
        'surface-deep-black': '#0D0C11',
        'surface-container-low': '#16151C',
        'surface-container': '#1F1D26',
        'border-hairline': '#2A2833',
        'primary': '#D0BCFF',
        'action-lavender': '#D0BCFF',
        'on-primary': '#381E72',
        'surface-bright': '#1F1D26',
        'outline': '#2A2833',
        'background': '#0D0C11',
        // Legacy aliases (kept for compatibility; values aligned to v3)
        'system-green': '#B9F2C8',
        'display-mint': '#B9F2C8',
        'accent-pink': '#FFD8E4',
        'human-orange': '#FFD6A5',
      },
      borderRadius: {
        'sm': '4px',
        'md': '12px',
        'DEFAULT': '16px',
        'lg': '16px',
        'xl': '24px',
        'folder': '24px',
        'full': '9999px',
      },
      spacing: {
        'margin-mobile': '1.5rem',
        'stack-sm': '1rem',
        'gutter': '1.5rem',
        'container-max': '1320px',
        'margin-desktop': '4rem',
        'stack-md': '2rem',
        'stack-lg': '4rem',
      },
      fontFamily: {
        'label-caps': ['IBM Plex Mono', 'JetBrains Mono', 'monospace'],
        'label-md': ['Hanken Grotesk', 'Inter', 'sans-serif'],
        'display-hero': ['Anton', 'Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'display-hero-mobile': ['Anton', 'Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'display': ['Anton', 'Hanken Grotesk', 'sans-serif'],
        'body': ['Hanken Grotesk', 'sans-serif'],
        'serif': ['Merriweather', 'Georgia', 'serif'],
        'mono': ['IBM Plex Mono', 'JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'label-caps': ['clamp(0.72rem, 0.8vw, 0.85rem)', { lineHeight: '1.4', letterSpacing: '0.18em', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'display-hero': ['clamp(4.5rem, 14.5vw, 11rem)', { lineHeight: '0.92', letterSpacing: '0', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['clamp(2.75rem, 6vw, 5.5rem)', { lineHeight: '1.05', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['clamp(1rem, 1.6vw, 1.55rem)', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
