/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'midnight-base': '#0B0F14',
        'dark-surface': '#141922',
        'elevated-surface': '#1C2330',
        'lavender': '#C8B6FF',
        'system-green': '#B8E6D0',
        'human-orange': '#FFD6A5',
        'soft-white': '#F2F2F5',
        'cool-grey': '#A7ADB8',
        'dim-grey': '#707784',
        'on-surface': '#F2F2F5',
        'on-surface-variant': '#A7ADB8',
        'surface-deep-black': '#0B0F14',
        'surface-container-low': '#141922',
        'surface-container': '#1C2330',
        'border-hairline': 'rgba(255, 255, 255, 0.12)',
        'primary': '#C8B6FF',
        'action-lavender': '#C8B6FF',
        'display-mint': '#B8E6D0',
        'accent-pink': '#FFD6A5',
        'on-primary': '#352564',
        'surface-bright': '#1C2330',
        'outline': 'rgba(255, 255, 255, 0.12)',
        'background': '#0B0F14',
      },
      borderRadius: {
        'sm': '4px',
        'md': '12px',
        'DEFAULT': '16px',
        'lg': '16px',
        'xl': '24px',
        'full': '9999px',
      },
      spacing: {
        'margin-mobile': '1.5rem',
        'stack-sm': '1rem',
        'gutter': '1.5rem',
        'container-max': '1280px',
        'margin-desktop': '4rem',
        'stack-md': '2rem',
        'stack-lg': '4rem',
      },
      fontFamily: {
        'label-caps': ['IBM Plex Mono', 'JetBrains Mono', 'monospace'],
        'label-md': ['Inter', 'sans-serif'],
        'display-hero': ['Anton', 'Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-hero-mobile': ['Anton', 'Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display': ['Anton', 'Inter', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'mono': ['IBM Plex Mono', 'JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'label-caps': ['clamp(0.8rem, 1.1vw, 1.05rem)', { lineHeight: '1.2', letterSpacing: '0.08em', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'display-hero': ['clamp(2.6rem, 14.5vw, 13rem)', { lineHeight: '0.92', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['clamp(2.8rem, 7.6vw, 6.4rem)', { lineHeight: '1.05', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['clamp(1rem, 1.6vw, 1.55rem)', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
